// Mocks generated by Mockito 5.4.4 from annotations
// in museflow/test/services/ai/cache/cache_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:museflow/models/ai_config.dart' as _i3;
import 'package:museflow/models/ai_message.dart' as _i8;
import 'package:museflow/models/ai_response.dart' as _i4;
import 'package:museflow/services/ai/ai_service.dart' as _i6;
import 'package:museflow/services/ai/cache/ai_cache_stats.dart' as _i5;
import 'package:museflow/services/ai/cache/cache_manager.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCacheManager_0 extends _i1.SmartFake implements _i2.CacheManager {
  _FakeCacheManager_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAIConfig_1 extends _i1.SmartFake implements _i3.AIConfig {
  _FakeAIConfig_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAIResponse_2 extends _i1.SmartFake implements _i4.AIResponse {
  _FakeAIResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAICacheStats_3 extends _i1.SmartFake implements _i5.AICacheStats {
  _FakeAICacheStats_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCachePerformanceMetrics_4 extends _i1.SmartFake
    implements _i2.CachePerformanceMetrics {
  _FakeCachePerformanceMetrics_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AIService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAIService extends _i1.Mock implements _i6.AIService {
  MockAIService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CacheManager get cacheManager => (super.noSuchMethod(
        Invocation.getter(#cacheManager),
        returnValue: _FakeCacheManager_0(
          this,
          Invocation.getter(#cacheManager),
        ),
      ) as _i2.CacheManager);

  @override
  _i7.Stream<_i2.CacheManagerEvent> get cacheEvents => (super.noSuchMethod(
        Invocation.getter(#cacheEvents),
        returnValue: _i7.Stream<_i2.CacheManagerEvent>.empty(),
      ) as _i7.Stream<_i2.CacheManagerEvent>);

  @override
  _i7.Future<_i3.AIConfig> addConfig(_i3.AIConfig? config) =>
      (super.noSuchMethod(
        Invocation.method(
          #addConfig,
          [config],
        ),
        returnValue: _i7.Future<_i3.AIConfig>.value(_FakeAIConfig_1(
          this,
          Invocation.method(
            #addConfig,
            [config],
          ),
        )),
      ) as _i7.Future<_i3.AIConfig>);

  @override
  _i7.Future<List<_i3.AIConfig>> getConfigs() => (super.noSuchMethod(
        Invocation.method(
          #getConfigs,
          [],
        ),
        returnValue: _i7.Future<List<_i3.AIConfig>>.value(<_i3.AIConfig>[]),
      ) as _i7.Future<List<_i3.AIConfig>>);

  @override
  _i7.Future<_i3.AIConfig?> getConfig(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getConfig,
          [id],
        ),
        returnValue: _i7.Future<_i3.AIConfig?>.value(),
      ) as _i7.Future<_i3.AIConfig?>);

  @override
  _i7.Future<void> deleteConfig(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteConfig,
          [id],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> setActiveConfig(String? id) => (super.noSuchMethod(
        Invocation.method(
          #setActiveConfig,
          [id],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i3.AIConfig?> getActiveConfig() => (super.noSuchMethod(
        Invocation.method(
          #getActiveConfig,
          [],
        ),
        returnValue: _i7.Future<_i3.AIConfig?>.value(),
      ) as _i7.Future<_i3.AIConfig?>);

  @override
  _i7.Future<_i4.AIResponse> sendMessage(
    List<_i8.AIMessage>? messages, {
    _i3.AIConfig? config,
    int? retryCount,
    bool? useCache = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendMessage,
          [messages],
          {
            #config: config,
            #retryCount: retryCount,
            #useCache: useCache,
          },
        ),
        returnValue: _i7.Future<_i4.AIResponse>.value(_FakeAIResponse_2(
          this,
          Invocation.method(
            #sendMessage,
            [messages],
            {
              #config: config,
              #retryCount: retryCount,
              #useCache: useCache,
            },
          ),
        )),
      ) as _i7.Future<_i4.AIResponse>);

  @override
  _i7.Stream<_i4.AIStreamChunk> sendMessageStream(
    List<_i8.AIMessage>? messages, {
    _i3.AIConfig? config,
    int? retryCount,
    void Function(_i4.AIStreamChunk)? onChunk,
    bool? useCache = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendMessageStream,
          [messages],
          {
            #config: config,
            #retryCount: retryCount,
            #onChunk: onChunk,
            #useCache: useCache,
          },
        ),
        returnValue: _i7.Stream<_i4.AIStreamChunk>.empty(),
      ) as _i7.Stream<_i4.AIStreamChunk>);

  @override
  _i7.Future<bool> validateApiKey(_i3.AIConfig? config) => (super.noSuchMethod(
        Invocation.method(
          #validateApiKey,
          [config],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<List<String>> getAvailableModels(_i3.AIConfig? config) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAvailableModels,
          [config],
        ),
        returnValue: _i7.Future<List<String>>.value(<String>[]),
      ) as _i7.Future<List<String>>);

  @override
  int estimateTokens(
    List<_i8.AIMessage>? messages,
    _i3.AIConfig? config,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #estimateTokens,
          [
            messages,
            config,
          ],
        ),
        returnValue: 0,
      ) as int);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<_i5.AICacheStats> getCacheStats() => (super.noSuchMethod(
        Invocation.method(
          #getCacheStats,
          [],
        ),
        returnValue: _i7.Future<_i5.AICacheStats>.value(_FakeAICacheStats_3(
          this,
          Invocation.method(
            #getCacheStats,
            [],
          ),
        )),
      ) as _i7.Future<_i5.AICacheStats>);

  @override
  _i7.Future<String> getCachePerformanceReport() => (super.noSuchMethod(
        Invocation.method(
          #getCachePerformanceReport,
          [],
        ),
        returnValue: _i7.Future<String>.value(_i9.dummyValue<String>(
          this,
          Invocation.method(
            #getCachePerformanceReport,
            [],
          ),
        )),
      ) as _i7.Future<String>);

  @override
  _i7.Future<Map<String, dynamic>> getCacheHealthStatus() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCacheHealthStatus,
          [],
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<void> clearCache({bool? clearExpiredOnly = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [],
          {#clearExpiredOnly: clearExpiredOnly},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void resetCacheStats() => super.noSuchMethod(
        Invocation.method(
          #resetCacheStats,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setCachingEnabled(bool? enabled) => super.noSuchMethod(
        Invocation.method(
          #setCachingEnabled,
          [enabled],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<_i2.CachePerformanceMetrics> getCachePerformanceMetrics() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachePerformanceMetrics,
          [],
        ),
        returnValue: _i7.Future<_i2.CachePerformanceMetrics>.value(
            _FakeCachePerformanceMetrics_4(
          this,
          Invocation.method(
            #getCachePerformanceMetrics,
            [],
          ),
        )),
      ) as _i7.Future<_i2.CachePerformanceMetrics>);

  @override
  _i7.Future<List<String>> getCacheSuggestions() => (super.noSuchMethod(
        Invocation.method(
          #getCacheSuggestions,
          [],
        ),
        returnValue: _i7.Future<List<String>>.value(<String>[]),
      ) as _i7.Future<List<String>>);

  @override
  _i7.Future<void> optimizeCacheStrategy() => (super.noSuchMethod(
        Invocation.method(
          #optimizeCacheStrategy,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> warmupCache(
    List<_i8.AIMessage>? commonMessages,
    _i3.AIConfig? config,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #warmupCache,
          [
            commonMessages,
            config,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}
