import 'dart:async';

import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:hive_ce_flutter/hive_flutter.dart';
import 'package:museflow/app.dart';
import 'package:museflow/core/infrastructure/hive_adapters.dart';
import 'package:museflow/core/infrastructure/secure_storage_service.dart';
import 'package:museflow/core/infrastructure/settings_repository.dart';
import 'package:museflow/core/infrastructure/temporary_hive_workspace.dart';
import 'package:museflow/core/platform/trace_marker.dart';
import 'package:museflow/core/platform/window_controller.dart';
import 'package:museflow/core/platform/web_workspace_mode.dart';
import 'package:museflow/features/manuscript/infrastructure/chapter_repository.dart';
import 'package:museflow/features/manuscript/infrastructure/manuscript_purge_service.dart';
import 'package:museflow/features/manuscript/infrastructure/manuscript_repository.dart';

/// Upper bound for the startup settings-box open, which reads/writes platform
/// secure storage. On Linux without a running Secret Service (WSL, minimal
/// window managers) libsecret calls can block indefinitely — startup must
/// fall back to defaults instead of hanging before the first frame.
const _settingsOpenTimeout = Duration(seconds: 5);

/// Opens the encrypted 'settings' box before [runApp] and reads the saved
/// window geometry from it. The box is left open — the router's first-run
/// redirect reads `onboarding_completed` from it synchronously, and
/// [settingsRepositoryProvider] reuses it via same-name open semantics.
///
/// Opening the box here (instead of lazily in the provider) also fixes the
/// fresh-install redirect: the box used to be closed on first launch, so
/// `Hive.box('settings')` threw inside the redirect guard, the error was
/// swallowed, and new users landed on the manuscript library instead of the
/// onboarding wizard.
Future<({Size? size, Offset? position})> _openSettingsAndReadGeometry() async {
  try {
    final box = await openSettingsBox(
      SecureStorageService(),
    ).timeout(_settingsOpenTimeout);

    Size? savedSize;
    final sizeData = box.get('windowSize');
    if (sizeData != null) {
      savedSize = Size(
        sizeData['width'] as double,
        sizeData['height'] as double,
      );
    }

    Offset? savedPosition;
    final posData = box.get('windowPosition');
    if (posData != null) {
      savedPosition = Offset(posData['x'] as double, posData['y'] as double);
    }

    return (size: savedSize, position: savedPosition);
  } catch (_) {
    // Key corrupted, secure storage unavailable, or the open timed out —
    // fall back to defaults. The box stays closed and the redirect guard
    // degrades to its no-redirect path until a later successful open.
    return (size: null, position: null);
  }
}

void main() async {
  setTraceMarker('1.binding');
  WidgetsFlutterBinding.ensureInitialized();
  setTraceMarker('2.hive-init');

  // Initialize Hive for local storage
  await Hive.initFlutter();
  setTraceMarker('3.adapters');

  // Register Hive type adapters (generated by build_runner)
  Hive.registerAdapter(FragmentAdapter());
  Hive.registerAdapter(AppSettingsAdapter());
  Hive.registerAdapter(CharacterCardAdapter());
  Hive.registerAdapter(WorldSettingAdapter());
  Hive.registerAdapter(SkillDocumentAdapter());
  Hive.registerAdapter(ForeshadowingEntryAdapter());
  Hive.registerAdapter(PlotNodeAdapter());
  Hive.registerAdapter(GuardianAnnotationAdapter());
  Hive.registerAdapter(ManuscriptAdapter());
  Hive.registerAdapter(ChapterAdapter());
  Hive.registerAdapter(TokenAuditRecordAdapter());
  Hive.registerAdapter(ChapterSummaryAdapter());

  if (kIsWeb && isTemporaryWebWorkspace) {
    await openTemporaryHiveWorkspace();
  }
  setTraceMarker('4.purge');

  // Purge soft-deleted manuscripts older than 30 days (D-21).
  // Non-critical startup task -- skipped on Web where IndexedDB access
  // may behave differently, and window geometry persistence is irrelevant.
  if (!kIsWeb) {
    try {
      final manuscriptsBox = await Hive.openBox<dynamic>('manuscripts');
      final chaptersBox = await Hive.openBox<dynamic>('chapters');
      final purgeService = ManuscriptPurgeService(
        manuscriptRepository: ManuscriptRepository(manuscriptsBox),
        chapterRepository: ChapterRepository(chaptersBox),
      );
      final purged = await purgeService.purgeExpired();
      if (purged > 0) {
        debugPrint(
          'ManuscriptPurgeService: purged $purged expired manuscripts',
        );
      }
    } catch (e) {
      debugPrint('ManuscriptPurgeService: purge failed (non-critical): $e');
    }
  }
  setTraceMarker('5.geometry');

  // Open the encrypted settings box (creating the Hive encryption key on
  // first launch) and read saved window geometry. Also runs on Web: the
  // router's first-run redirect reads `onboarding_completed` synchronously,
  // and skipping the pre-runApp open here used to swallow a HiveError and
  // strand fresh web users on the library instead of the onboarding wizard.
  // The [_settingsOpenTimeout] guard keeps a wedged secure-storage backend
  // from hanging startup; on failure the redirect degrades to no-redirect.
  // Temporary workspaces keep their own in-memory settings box and must not
  // touch the persistent encryption-key path at all.
  final geometry = (kIsWeb && isTemporaryWebWorkspace)
      ? (size: null as Size?, position: null as Offset?)
      : await _openSettingsAndReadGeometry();
  setTraceMarker('6.platform');

  if (!kIsWeb) {
    await configurePlatformWindow(
      savedSize: geometry.size,
      savedPosition: geometry.position,
    );
  }
  setTraceMarker('7.runApp');

  runApp(const ProviderScope(child: MuseFlowApp()));
  setTraceMarker('8.done');
}
