/// Author style profile — analyzed writing style across 5 dimensions.
///
/// Immutable domain entity representing the quantified writing style
/// of an author for a specific manuscript. Generated by [StyleAnalyzer]
/// and persisted in Hive. Used by [DynamicPersonaMiddleware] and
/// [FewShotMiddleware] to personalize AI output.
library;

import 'package:museflow/features/editor/domain/lexical_signature.dart';
import 'package:museflow/features/editor/domain/style_sample.dart';

/// Sentence length statistics for the author's writing.
class SentenceLengthStats {
  final double avg;
  final double stdDev;
  final double median;
  final double shortRatio; // <15 chars
  final double longRatio; // >40 chars

  const SentenceLengthStats({
    this.avg = 0,
    this.stdDev = 0,
    this.median = 0,
    this.shortRatio = 0,
    this.longRatio = 0,
  });

  SentenceLengthStats copyWith({
    double? avg,
    double? stdDev,
    double? median,
    double? shortRatio,
    double? longRatio,
  }) {
    return SentenceLengthStats(
      avg: avg ?? this.avg,
      stdDev: stdDev ?? this.stdDev,
      median: median ?? this.median,
      shortRatio: shortRatio ?? this.shortRatio,
      longRatio: longRatio ?? this.longRatio,
    );
  }

  factory SentenceLengthStats.fromJson(Map<String, dynamic> json) {
    return SentenceLengthStats(
      avg: (json['avg'] as num).toDouble(),
      stdDev: (json['stdDev'] as num).toDouble(),
      median: (json['median'] as num).toDouble(),
      shortRatio: (json['shortRatio'] as num).toDouble(),
      longRatio: (json['longRatio'] as num).toDouble(),
    );
  }

  Map<String, dynamic> toJson() => {
    'avg': avg,
    'stdDev': stdDev,
    'median': median,
    'shortRatio': shortRatio,
    'longRatio': longRatio,
  };
}

/// Rhetoric habits — ratios of different writing modes.
class RhetoricHabits {
  final double metaphorFrequency;
  final double dialogueRatio;
  final double descriptionRatio;
  final double actionRatio;

  const RhetoricHabits({
    this.metaphorFrequency = 0,
    this.dialogueRatio = 0,
    this.descriptionRatio = 0,
    this.actionRatio = 0,
  });

  RhetoricHabits copyWith({
    double? metaphorFrequency,
    double? dialogueRatio,
    double? descriptionRatio,
    double? actionRatio,
  }) {
    return RhetoricHabits(
      metaphorFrequency: metaphorFrequency ?? this.metaphorFrequency,
      dialogueRatio: dialogueRatio ?? this.dialogueRatio,
      descriptionRatio: descriptionRatio ?? this.descriptionRatio,
      actionRatio: actionRatio ?? this.actionRatio,
    );
  }

  factory RhetoricHabits.fromJson(Map<String, dynamic> json) {
    return RhetoricHabits(
      metaphorFrequency: (json['metaphorFrequency'] as num?)?.toDouble() ?? 0,
      dialogueRatio: (json['dialogueRatio'] as num?)?.toDouble() ?? 0,
      descriptionRatio: (json['descriptionRatio'] as num?)?.toDouble() ?? 0,
      actionRatio: (json['actionRatio'] as num?)?.toDouble() ?? 0,
    );
  }

  Map<String, dynamic> toJson() => {
    'metaphorFrequency': metaphorFrequency,
    'dialogueRatio': dialogueRatio,
    'descriptionRatio': descriptionRatio,
    'actionRatio': actionRatio,
  };
}

/// Emotional tone analysis results.
class EmotionalTone {
  final String overall; // e.g., "温暖克制", "热烈奔放"
  final double warmth; // 0.0–1.0
  final double intensity; // 0.0–1.0

  const EmotionalTone({
    this.overall = '',
    this.warmth = 0.5,
    this.intensity = 0.5,
  });

  EmotionalTone copyWith({String? overall, double? warmth, double? intensity}) {
    return EmotionalTone(
      overall: overall ?? this.overall,
      warmth: warmth ?? this.warmth,
      intensity: intensity ?? this.intensity,
    );
  }

  factory EmotionalTone.fromJson(Map<String, dynamic> json) {
    return EmotionalTone(
      overall: json['overall'] as String? ?? '',
      warmth: (json['warmth'] as num?)?.toDouble() ?? 0.5,
      intensity: (json['intensity'] as num?)?.toDouble() ?? 0.5,
    );
  }

  Map<String, dynamic> toJson() => {
    'overall': overall,
    'warmth': warmth,
    'intensity': intensity,
  };
}

/// Author style profile — quantified writing style across 5 dimensions.
///
/// Analyzed from the author's existing chapters and used to personalize
/// AI prompts. One profile per manuscript, updated incrementally as
/// the author writes more chapters.
class AuthorStyleProfile {
  /// The manuscript this profile belongs to.
  final String manuscriptId;

  /// Sentence length statistics.
  final SentenceLengthStats sentenceLengthStats;

  /// Rhythm/burstiness score (0.0 = very varied, 1.0 = very uniform).
  final double rhythmScore;

  /// Vocabulary richness (0.0 = repetitive, 1.0 = very diverse).
  final double vocabularyRichness;

  /// Rhetoric habit ratios.
  final RhetoricHabits rhetoricHabits;

  /// Emotional tone analysis.
  final EmotionalTone emotionalTone;

  /// Author's characteristic CJK n-gram vocabulary (bigrams + trigrams).
  ///
  /// Captures the actual words the author favors, complementing the scalar
  /// [vocabularyRichness] ratio. Injected by DynamicPersonaMiddleware into
  /// generation prompts so the AI internalizes the author's vocabulary palette.
  final LexicalSignature lexicalSignature;

  /// Number of chapters analyzed.
  final int analyzedChapterCount;

  /// Total CJK characters analyzed.
  final int analyzedCharCount;

  /// When this profile was last updated.
  final DateTime lastAnalyzedAt;

  /// Top quality paragraphs extracted as few-shot style samples.
  final List<StyleSample> sampleParagraphs;

  AuthorStyleProfile({
    required this.manuscriptId,
    this.sentenceLengthStats = const SentenceLengthStats(),
    this.rhythmScore = 0.5,
    this.vocabularyRichness = 0.5,
    this.rhetoricHabits = const RhetoricHabits(),
    this.emotionalTone = const EmotionalTone(),
    this.lexicalSignature = const LexicalSignature(),
    this.analyzedChapterCount = 0,
    this.analyzedCharCount = 0,
    DateTime? lastAnalyzedAt,
    this.sampleParagraphs = const [],
  }) : lastAnalyzedAt = lastAnalyzedAt ?? DateTime.now();

  AuthorStyleProfile copyWith({
    String? manuscriptId,
    SentenceLengthStats? sentenceLengthStats,
    double? rhythmScore,
    double? vocabularyRichness,
    RhetoricHabits? rhetoricHabits,
    EmotionalTone? emotionalTone,
    LexicalSignature? lexicalSignature,
    int? analyzedChapterCount,
    int? analyzedCharCount,
    DateTime? lastAnalyzedAt,
    List<StyleSample>? sampleParagraphs,
  }) {
    return AuthorStyleProfile(
      manuscriptId: manuscriptId ?? this.manuscriptId,
      sentenceLengthStats: sentenceLengthStats ?? this.sentenceLengthStats,
      rhythmScore: rhythmScore ?? this.rhythmScore,
      vocabularyRichness: vocabularyRichness ?? this.vocabularyRichness,
      rhetoricHabits: rhetoricHabits ?? this.rhetoricHabits,
      emotionalTone: emotionalTone ?? this.emotionalTone,
      lexicalSignature: lexicalSignature ?? this.lexicalSignature,
      analyzedChapterCount: analyzedChapterCount ?? this.analyzedChapterCount,
      analyzedCharCount: analyzedCharCount ?? this.analyzedCharCount,
      lastAnalyzedAt: lastAnalyzedAt ?? this.lastAnalyzedAt,
      sampleParagraphs: sampleParagraphs ?? this.sampleParagraphs,
    );
  }

  factory AuthorStyleProfile.fromJson(Map<String, dynamic> json) {
    return AuthorStyleProfile(
      manuscriptId: json['manuscriptId'] as String,
      sentenceLengthStats: json['sentenceLengthStats'] != null
          ? SentenceLengthStats.fromJson(
              json['sentenceLengthStats'] as Map<String, dynamic>,
            )
          : const SentenceLengthStats(),
      rhythmScore: (json['rhythmScore'] as num?)?.toDouble() ?? 0.5,
      vocabularyRichness:
          (json['vocabularyRichness'] as num?)?.toDouble() ?? 0.5,
      rhetoricHabits: json['rhetoricHabits'] != null
          ? RhetoricHabits.fromJson(
              json['rhetoricHabits'] as Map<String, dynamic>,
            )
          : const RhetoricHabits(),
      emotionalTone: json['emotionalTone'] != null
          ? EmotionalTone.fromJson(
              json['emotionalTone'] as Map<String, dynamic>,
            )
          : const EmotionalTone(),
      lexicalSignature: json['lexicalSignature'] != null
          ? LexicalSignature.fromJson(
              json['lexicalSignature'] as Map<String, dynamic>,
            )
          : const LexicalSignature(),
      analyzedChapterCount: json['analyzedChapterCount'] as int? ?? 0,
      analyzedCharCount: json['analyzedCharCount'] as int? ?? 0,
      lastAnalyzedAt: json['lastAnalyzedAt'] != null
          ? DateTime.parse(json['lastAnalyzedAt'] as String)
          : DateTime.now(),
      sampleParagraphs:
          (json['sampleParagraphs'] as List<dynamic>?)
              ?.map((s) => StyleSample.fromJson(s as Map<String, dynamic>))
              .toList() ??
          [],
    );
  }

  Map<String, dynamic> toJson() => {
    'manuscriptId': manuscriptId,
    'sentenceLengthStats': sentenceLengthStats.toJson(),
    'rhythmScore': rhythmScore,
    'vocabularyRichness': vocabularyRichness,
    'rhetoricHabits': rhetoricHabits.toJson(),
    'emotionalTone': emotionalTone.toJson(),
    'lexicalSignature': lexicalSignature.toJson(),
    'analyzedChapterCount': analyzedChapterCount,
    'analyzedCharCount': analyzedCharCount,
    'lastAnalyzedAt': lastAnalyzedAt.toIso8601String(),
    'sampleParagraphs': sampleParagraphs.map((s) => s.toJson()).toList(),
  };

  /// Whether this profile has enough data to be useful.
  bool get hasData => analyzedChapterCount >= 2 && analyzedCharCount >= 500;

  @override
  bool operator ==(Object other) {
    return other is AuthorStyleProfile &&
        other.manuscriptId == manuscriptId &&
        other.lastAnalyzedAt == lastAnalyzedAt;
  }

  @override
  int get hashCode => Object.hash(manuscriptId, lastAnalyzedAt);
}
